--Delete script
delete from citizengrid_applicationec2images;
delete from citizengrid_applicationopenstackimages;
delete from citizengrid_applicationclientinfo;
delete from citizengrid_applicationserverinfo;
delete from citizengrid_applicationbasicinfo;
delete from citizengrid_applicationfile;
